name: house_launcher

description: House Launcher

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_apps: ^2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/room.jpg